# Generated by Django 3.2.3 on 2021-06-22 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20210622_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_payment',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 14, 27, 21, 989019)),
        ),
        migrations.AlterField(
            model_name='contact_detail',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 14, 27, 21, 980018)),
        ),
        migrations.AlterField(
            model_name='corderbooking',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 14, 27, 21, 987018)),
        ),
        migrations.AlterField(
            model_name='current_stock',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 14, 27, 21, 990019)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 14, 27, 21, 987018)),
        ),
        migrations.AlterField(
            model_name='daily_expense',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 14, 27, 21, 989019)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 14, 27, 21, 977018)),
        ),
        migrations.AlterField(
            model_name='personal_data',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 14, 27, 21, 977018)),
        ),
        migrations.AlterField(
            model_name='previous_experience',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 14, 27, 21, 979018)),
        ),
        migrations.AlterField(
            model_name='product',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 14, 27, 21, 983018)),
        ),
        migrations.AlterField(
            model_name='product_category',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 14, 27, 21, 981018)),
        ),
        migrations.AlterField(
            model_name='product_type',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 14, 27, 21, 982018)),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 14, 27, 21, 978018)),
        ),
        migrations.AlterField(
            model_name='s_contact_detail',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 14, 27, 21, 986018)),
        ),
        migrations.AlterField(
            model_name='s_contact_person',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 14, 27, 21, 986018)),
        ),
        migrations.AlterField(
            model_name='s_order_booking',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 14, 27, 21, 984018)),
        ),
        migrations.AlterField(
            model_name='s_payment',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 14, 27, 21, 985018)),
        ),
        migrations.AlterField(
            model_name='skills',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 14, 27, 21, 980018)),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 14, 27, 21, 981018)),
        ),
    ]
