# Generated by Django 3.2.3 on 2021-06-22 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20210622_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_payment',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 14, 57, 2, 351793)),
        ),
        migrations.AlterField(
            model_name='contact_detail',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 14, 57, 2, 342793)),
        ),
        migrations.AlterField(
            model_name='corderbooking',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 14, 57, 2, 349793)),
        ),
        migrations.AlterField(
            model_name='current_stock',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 14, 57, 2, 352793)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 14, 57, 2, 349793)),
        ),
        migrations.AlterField(
            model_name='daily_expense',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 14, 57, 2, 351793)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 14, 57, 2, 338792)),
        ),
        migrations.AlterField(
            model_name='personal_data',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 14, 57, 2, 339792)),
        ),
        migrations.AlterField(
            model_name='previous_experience',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 14, 57, 2, 341793)),
        ),
        migrations.AlterField(
            model_name='product',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 14, 57, 2, 344793)),
        ),
        migrations.AlterField(
            model_name='product_category',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 14, 57, 2, 343793)),
        ),
        migrations.AlterField(
            model_name='product_type',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 14, 57, 2, 344793)),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 14, 57, 2, 340792)),
        ),
        migrations.AlterField(
            model_name='s_contact_detail',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 14, 57, 2, 347793)),
        ),
        migrations.AlterField(
            model_name='s_contact_person',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 14, 57, 2, 348793)),
        ),
        migrations.AlterField(
            model_name='s_order_booking',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 14, 57, 2, 345793)),
        ),
        migrations.AlterField(
            model_name='s_payment',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 14, 57, 2, 347793)),
        ),
        migrations.AlterField(
            model_name='skills',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 14, 57, 2, 341793)),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 14, 57, 2, 343793)),
        ),
    ]
