# Generated by Django 3.2.3 on 2021-06-19 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_reviews_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label_colour',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='item',
            name='labels',
            field=models.CharField(blank=True, choices=[('BestSeller', 'BestSeller'), ('New', 'New'), ('Unique', 'Unique'), ('Antique', 'Antique')], max_length=25),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='Jewellery_Shop'),
        ),
    ]
