# Generated by Django 3.2.3 on 2021-06-20 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20210620_0347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='item',
            name='label_colour',
        ),
    ]
